### ISSUE TITLE
Should consider using Sass for your project

### ISSUE THREAD

**Issue by tarebyte** [mattfxyz/mattfxyz.github.io#1]
So I was mentioning about [vendor prefixes](http://docs.emmet.io/css-abbreviations/vendor-prefixes/) and how they can be annoying.

If you use something like [Sass](http://sass-lang.com/) with [Bourbon](http://bourbon.io/) you can make your same animations with only one line.

Check it out!

**Comment by mattfaluotico** [comment]
wow this is old.
